pool_interval: 0.02
base_gravity: 0

commands:
  - command: 'light'
    stimulate: True
    at: 1
    module:
      1: True
      2: True
      3: True
      4: True

  - command: 'light'
    at: 3
    module:


  - command: 'electricity'
    stimulate: True
    at: 5
    module:
      1: True
      2: True
      3: True
      4: True

  - command: 'electricity'
    at: 7
    module:
      1: False
      2: False
      3: False
      4: False

  - command: 'beep setting'
    at: 9
    frequency: 3000
    module: 4

  - command: 'beep'
    stimulate: True
    at: 11
    module:
      1: True
      2: True
      3: True
      4: True


  - command: 'beep'
    at: 13
    module:
      1: False
      2: False
      3: False
      4: False

  - command: 'flash on'
    at: 15

  - command: 'end experiment'
    at: 17