pool_interval: 0.01
base_gravity: 0

commands:
  - command: 'light'
    stimulate: True
    at: 3
    module:
      1: True
      2: True
      3: True
      4: True

  - command: 'light'
    at: 8
    module:


  - command: 'electricity'
    stimulate: True
    at: 10
    module:
      1: True
      2: True
      3: True
      4: True

  - command: 'electricity'
    at: 12
    module:
      1: False
      2: False
      3: False
      4: False

  - command: 'beep setting'
    at: 14
    frequency: 5
    module: 3

  - command: 'beep setting'
    at: 14
    frequency: 100
    module: 4

  - command: 'beep'
    stimulate: True
    at: 15
    module:
      1: True
      2: True
      3: True
      4: True
      
 
  - command: 'beep'
    stimulate: True
    at: 17
    module:
      1: True
      2: True
      3: True
      4: True

  - command: 'beep'
    at: 21
    module:
      1: False
      2: False
      3: False
      4: False

  - command: 'flash on'
    at: 22

  - command: 'end experiment'
    at: 25