pool_interval: 0.01
commands:
  - command: 'light on'
    at: 3
  - command: 'light off'
    at: 8
  - command: 'electricity on'
    at: 10
  - command: 'electricity off'
    at: 12
  - command: 'noise setting'
    at: 14
    db: 20
    beep: beep2
  - command: 'noise on'
    at: 15
  - command: 'noise off'
    at: 16
  - command: 'flash on'
    at: 17
  - command: 'end experiment'
    at: 18