commands:
  - command: 'login'
    at: 0
  - command: 'light on'
    at: 3
  - command: 'light off'
    at: 8
  - command: '加电'
    at: 10
  - command: '关电'
    at: 12
  - command: 'noise on'
    at: 14
    db: 20
    beep: beep2
  - command: 'noise off'
    at: 16
  - command: 'end experiment'
    at: 18